### ISSUE TITLE
Scene issue

### ISSUE THREAD

**Issue by ryanpfister** [FIRST-South-Carolina/obs-ftc-stream-manager#1]
Getting this issue when using the FTCLive Software and this stream manager:
`[ftc-stream-manager.py] Traceback (most recent call last):
[ftc-stream-manager.py]   File "C:\Users/Ryan Pfister/Downloads/obs-ftc-stream-manager-main/obs-ftc-stream-manager-main\ftc-stream-manager.py", line 763, in check_websocket
[ftc-stream-manager.py]     current_scene_name = obs.obs_source_get_name()
[ftc-stream-manager.py]                          ^^^^^^^^^^^^^^^^^^^^^^^^^
[ftc-stream-manager.py] TypeError: obs_source_get_name() missing 1 required positional argument: 'source'`

**Comment by lilyinstarlight** [comment]
Hi there! It looks like I must have typo'd it. We admittedly used a modified version of this script in the most recent season to support with manual youtube upload for reasons, so I may have fixed it there and forgot to update the fix here

I'll try to lool at this later today, but I imagine `current_scene` probably just needs to be in the arguments. Thank you for the report!

Also, I'm curious: do you do A/V or are you FTA(A) for a particular _FIRST_ region?

**Comment by ryanpfister** [comment]
I was able to fix this by adding the argument 'current_scene' as you suggested, and made a pull request https://github.com/FIRST-South-Carolina/obs-ftc-stream-manager/pull/2

I am the lead scorekeepr and one of the leads on our A/V team for _FIRST_ Long Island in New York.
Thank you for the help, we will probably be using this amazing code for this upcoming FTC season, we are sort of tweaking some of our livestreaming setup since we want some more video on demand resources for teams to go back and refer to certain matches if they need. 

Thank again!

**Comment by lilyinstarlight** [comment]
Feel free to email me and add me on Discord or Matrix if you'd like! I'd love to work with you on it and assist with any problems or needed features

I did intend to add dual division support for a region last season but I admittedly never got around to it
